name: Build Flet APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet CLI
        run: |
          pip install flet
          
      - name: Build Android APK
        run: |
          # Официальный сборщик Flet сам создаст проект Flutter и упакует Python без сбоев SDK
          flet build apk --title "Goida AI Unlocker" --package-name "com.andeds.goidaunlocker"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Goida-APK
          path: build/apk/*.apk
